### ISSUE TITLE
Imported data is inconsistent.

### ISSUE THREAD

**Issue by Zapata** [oxarbitrage/bitshares-python-api-backend#21]
The way the data is imported in database is inconsistent, as there are blocks ingested by the core while all the assets/accounts/.. are retrieved.

Either the core should stop synchronize while the export is done, or the data should be loaded from a snapshot.

**Comment by oxarbitrage** [comment]
yes, thanks for submitting this. to be honest my plan is to eliminate the whole importation and all the postgres by the use of the `es_objects` plugin. 
i think we should focus our efforts in that rather than fixing this one. what you say of course makes sense.

let me know what do you think, will be great to have some collaboration here :)

**Comment by Zapata** [comment]
I think this could be closed as #42 has been merged.
